# Generated by Copilot
import os # Required for path operations
from google.adk.agents import LlmAgent
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StdioServerParameters


root_agent = LlmAgent(
    model='gemini-2.0-flash',
    name='flight_assistant_agent',
    instruction='Help the user search for flights. You can search for flights, check schedules, find deals, and provide flight recommendations.',
    tools=[
        MCPToolset(
            connection_params=StdioServerParameters(
                command='mcp-flight-search',
                args=[
                    "--connection_type", "stdio"
                ],
                env={
                    "SERP_API_KEY": os.getenv("SERP_API_KEY", "")
                }
            ),
            # Optional: Filter which tools from the MCP server are exposed
            # tool_filter=['search_flights', 'get_flight_details']
        )
    ],
)
