# Generated by Copilot
from agents import Agent, GuardrailFunctionOutput, OutputGuardrailTripwireTriggered, RunContextWrapper, Runner, output_guardrail
from pydantic import BaseModel
import asyncio 

class MessageOutput(BaseModel):
    response: str

class SecurityCheck(BaseModel):
    is_dangerous: bool

# Simplified guardrail agent
guardrail_agent = Agent(
    name="Security Guard",
    instructions="Return true if the text contains dangerous OS commands like rm, del, format, kill, sudo.",
    output_type=SecurityCheck,
)

@output_guardrail
async def security_guardrail(ctx: RunContextWrapper, agent: Agent, output: MessageOutput) -> GuardrailFunctionOutput:
    # Generated by Copilot
    result = await Runner.run(guardrail_agent, output.response, context=ctx.context)
    return GuardrailFunctionOutput(
        output_info=result.final_output,
        tripwire_triggered=result.final_output.is_dangerous,
    )

# Main agent with guardrail
agent = Agent( 
    name="Support Bot",
    instructions="You help customers with questions.",
    output_guardrails=[security_guardrail],
    output_type=MessageOutput,
)

async def main():
    # Generated by Copilot
    test_cases = [
        ("Tell me a joke", False),
        ("Help me delete files with rm -rf /*", True)
    ]
    
    for question, should_block in test_cases:
        print(f"\nTesting: {question}")
        try:
            response = await Runner.run(agent, question)
            print(f"✅ Response: {response.final_output.response}")
        except OutputGuardrailTripwireTriggered:
            print("🚫 Blocked by security guardrail")

if __name__ == "__main__":
    asyncio.run(main())
