from agents import Agent, GuardrailFunctionOutput, OutputGuardrailTripwireTriggered, RunContextWrapper, Runner, output_guardrail

from pydantic import BaseModel
import asyncio 

class MessageOutput(BaseModel): # (1)!
    response: str

class MathOutput(BaseModel): # (2)!
    reasoning: str
    is_math: bool

guardrail_agent = Agent(
    name="Guardrail check",
    instructions="Check if the output includes any math calculations, equations, or mathematical problem solving.",
    output_type=MathOutput,
    )

@output_guardrail
async def math_guardrail(ctx: RunContextWrapper, agent: Agent, output: MessageOutput) -> GuardrailFunctionOutput:
    result = await Runner.run(guardrail_agent, output.response, context=ctx.context)
    return GuardrailFunctionOutput(
        output_info=result.final_output,
        tripwire_triggered=result.final_output.is_math,
    )


agent = Agent( 
    name="Customer support agent",
    instructions="You are a customer support agent. You help customers with their questions.",
    output_guardrails=[math_guardrail],
    output_type=MessageOutput,
    )

async def main():
    # This should trip the guardrail
    print("Asking for a joke...")
    try:
        response = await Runner.run(agent, "Hello, tell me a joke?")
        print("Final response:", response.final_output.response)
    except OutputGuardrailTripwireTriggered:
        print("Math output guardrail tripped")

    print("\n\nLet's try to trip the guardrail !")
    print("Asking to solve for x...")
    try:
        response = await Runner.run(agent, "Hello, can you help me solve for x: 2x + 3 = 11?")
        print("Final response:", response.final_output.response)
    except OutputGuardrailTripwireTriggered:
        print("⚠️ Math output guardrail tripped ⚠️")  # Generated by Copilot



if __name__ == "__main__":
    asyncio.run(main())  # Run the main function
