services:
  app:
    build: .
    container_name: lab040_rag
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bash
