#!/usr/bin/env python3
import warnings
from mem0 import MemoryClient

# Suppress deprecation warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="mem0")

# Initialize the client
client = MemoryClient()

# Test basic functionality
messages = [
    {"role": "user", "content": "My name is Philippe and I love Python programming"},
    {"role": "assistant", "content": "Nice to meet you Philippe! I'll remember that you love Python programming."}
]

# Add memory
result = client.add(messages, user_id="demo-user", version="v2")
print("Added memory:", result)

# Search memory
search_results = client.search("What's my name?", user_id="demo-user", version="v2")
print("\nSearch results:")
for item in search_results:
    print(f"- {item.get('memory', item)}")

# Get all memories
all_memories = client.get_all(user_id="demo-user", version="v2")
print(f"\nAll memories ({len(all_memories.get('results', []))} total):")
for item in all_memories.get('results', []):
    print(f"- {item.get('memory', item)}")

print("\n✅ Mem0 is working correctly without warnings!")

# Generated by Copilot
