# Cleanup
# Generated by Copilot

# Define a portable cecho function for colored output
cecho() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "$@"
    else
        echo -e "$@"
    fi
}

export LAB=".$(basename "$PWD")"
echo "================================================================================"
echo "Cleaning up $LAB"
echo "================================================================================"
if [ -d "$LAB" ]; then
    rm -rf "$LAB"
    cecho "\033[31mRemoved virtual environment: $LAB\033[0m"
else
    cecho "\033[33mNo virtual environment found to remove: $LAB\033[0m"
fi
echo "================================================================================"
cecho "\033[32mCleanup complete for $LAB\033[0m"
echo "================================================================================"
