# Setup
export LAB=".$(basename "$PWD")"
echo "================================================================================"
echo "Setting up $LAB"
echo "================================================================================"
python3 -m venv $LAB
source $LAB/bin/activate
# Generated by Copilot
if [ -f "requirements.txt" ]; then
    python3 -m venv $LAB
    source $LAB/bin/activate
    pip3 install -r requirements.txt
    echo "================================================================================"
    echo -e "Use \033[31msource $LAB/bin/activate\033[0m to activate the virtual environment"
    echo "================================================================================"
else
    echo "================================================================================"
    echo "requirements.txt not found, skipping python virtual env creation"
    echo "================================================================================"
fi
echo "$LAB setup complete"

echo "================================================================================"
echo -e "Don't forget the export your OPENAI API key \033[31mexport OPENAI_API_KEY=\"xxxxxxxxx\"\033[0m to activate the virtual environment"
echo "================================================================================"
