#!/usr/bin/env python3
"""
Interactive Kubernetes assistant using OpenAI function calling.

The LLM decides which kubectl command to run, the tool executes it locally,
and the model summarises the output.  Every kubectl invocation is logged to
an audit file under kubectl_audit_logs/.

Supports OPENAI_BASE_URL override (useful with mitmproxy).

Generated by Copilot, cleaned for lab use.
"""

import os
import json
import subprocess
import logging
import datetime
from openai import OpenAI


# ---- Logging -----------------------------------------------------------

def setup_logging():
    """Set up logging for kubectl command auditing."""
    log_dir = "kubectl_audit_logs"
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_filename = f"{log_dir}/kubectl_audit_{timestamp}.log"

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(log_filename),
            logging.StreamHandler(),
        ],
    )

    logger = logging.getLogger(__name__)
    logger.info("=== Starting Kubernetes Assistant Session ===")
    logger.info("Log file: %s", log_filename)
    return logger


def log_kubectl_command(logger, cmd, namespace=None, function_name=None,
                        success=True, error_msg=None):
    """Log kubectl command execution for auditing."""
    log_entry = {
        "timestamp": datetime.datetime.now().isoformat(),
        "function": function_name,
        "command": " ".join(cmd),
        "namespace": namespace,
        "success": success,
        "user": os.getenv("USER", "unknown"),
        "pwd": os.getcwd(),
    }
    if error_msg:
        log_entry["error"] = error_msg

    if success:
        logger.info("KUBECTL_SUCCESS: %s", json.dumps(log_entry))
    else:
        logger.error("KUBECTL_ERROR: %s", json.dumps(log_entry))


# ---- Kubectl check -----------------------------------------------------

def check_kubectl():
    """Return (True, msg) if kubectl is available, (False, msg) otherwise."""
    try:
        subprocess.run(["kubectl", "version", "--client"],
                       capture_output=True, check=True)
        return True, "kubectl is available"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False, "kubectl is not installed or not in PATH"


# ---- Tool schemas -------------------------------------------------------

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_kubernetes_pods",
            "description":
                "Get information about pods in a Kubernetes namespace.",
            "parameters": {
                "type": "object",
                "properties": {
                    "namespace": {
                        "type": "string",
                        "description":
                            "Kubernetes namespace (e.g. 'default', 'kube-system')",
                    },
                    "pod_status": {
                        "type": "string",
                        "description":
                            "Filter by status. Leave empty for all pods.",
                        "enum": [
                            "", "Running", "Pending",
                            "CrashLoopBackOff", "Failed", "Succeeded",
                        ],
                    },
                },
                "required": ["namespace"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_pod_logs",
            "description": "Get logs from a specific Kubernetes pod.",
            "parameters": {
                "type": "object",
                "properties": {
                    "namespace": {
                        "type": "string",
                        "description": "Kubernetes namespace",
                    },
                    "pod_name": {
                        "type": "string",
                        "description": "Name of the pod",
                    },
                    "lines": {
                        "type": "integer",
                        "description":
                            "Number of tail lines to retrieve (default 50)",
                        "default": 50,
                    },
                },
                "required": ["namespace", "pod_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "describe_pod",
            "description":
                "Get detailed information about a pod (kubectl describe).",
            "parameters": {
                "type": "object",
                "properties": {
                    "namespace": {
                        "type": "string",
                        "description": "Kubernetes namespace",
                    },
                    "pod_name": {
                        "type": "string",
                        "description": "Name of the pod",
                    },
                },
                "required": ["namespace", "pod_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "execute_kubectl_command",
            "description":
                "Execute any kubectl command. Fallback when other tools "
                "do not cover the request. Requires user confirmation.",
            "parameters": {
                "type": "object",
                "properties": {
                    "kubectl_args": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description":
                            "kubectl arguments, e.g. ['get', 'namespaces']",
                    },
                    "description": {
                        "type": "string",
                        "description":
                            "Human-readable description of the command",
                    },
                },
                "required": ["kubectl_args", "description"],
            },
        },
    },
]


# ---- Tool implementations -----------------------------------------------

def get_kubernetes_pods(logger, namespace, pod_status=""):
    cmd = ["kubectl", "get", "pods", "-n", namespace, "-o", "json"]
    try:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_kubernetes_pods")
        result = subprocess.run(cmd, capture_output=True, text=True,
                                check=True)
        return (f"kubectl get pods output for namespace "
                f"'{namespace}':\n{result.stdout}")
    except subprocess.CalledProcessError as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_kubernetes_pods",
                           success=False, error_msg=str(e.stderr))
        return f"Error running kubectl: {e.stderr}"
    except Exception as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_kubernetes_pods",
                           success=False, error_msg=str(e))
        return f"Error: {e}"


def get_pod_logs(logger, namespace, pod_name, lines=50):
    cmd = ["kubectl", "logs", pod_name, "-n", namespace,
           "--tail", str(lines)]
    try:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_pod_logs")
        result = subprocess.run(cmd, capture_output=True, text=True,
                                check=True)
        return (f"Logs for pod '{pod_name}' in namespace '{namespace}' "
                f"(last {lines} lines):\n{result.stdout}")
    except subprocess.CalledProcessError as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_pod_logs",
                           success=False, error_msg=str(e.stderr))
        return f"Error running kubectl logs: {e.stderr}"
    except Exception as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="get_pod_logs",
                           success=False, error_msg=str(e))
        return f"Error: {e}"


def describe_pod(logger, namespace, pod_name):
    cmd = ["kubectl", "describe", "pod", pod_name, "-n", namespace]
    try:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="describe_pod")
        result = subprocess.run(cmd, capture_output=True, text=True,
                                check=True)
        return (f"kubectl describe for pod '{pod_name}' in namespace "
                f"'{namespace}':\n{result.stdout}")
    except subprocess.CalledProcessError as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="describe_pod",
                           success=False, error_msg=str(e.stderr))
        return f"Error running kubectl describe: {e.stderr}"
    except Exception as e:
        log_kubectl_command(logger, cmd, namespace,
                           function_name="describe_pod",
                           success=False, error_msg=str(e))
        return f"Error: {e}"


def execute_kubectl_command(logger, kubectl_args, description):
    cmd = ["kubectl"] + kubectl_args
    cmd_str = " ".join(cmd)
    try:
        print(f"\n  SECURITY CONFIRMATION REQUIRED")
        print(f"  Command:     {cmd_str}")
        print(f"  Description: {description}")
        confirmation = input(
            "  Execute this command? [Y/n] (Enter = Yes): "
        ).strip().lower()

        logger.info("KUBECTL_CONFIRMATION_REQUESTED: %s",
                     json.dumps({"command": cmd_str,
                                 "description": description,
                                 "user": os.getenv("USER", "unknown")}))

        if confirmation in ("n", "no"):
            logger.info("KUBECTL_DENIED: %s",
                         json.dumps({"command": cmd_str,
                                     "user": os.getenv("USER", "unknown")}))
            return f"Command execution denied by user: {cmd_str}"

        logger.info("KUBECTL_APPROVED: %s",
                     json.dumps({"command": cmd_str,
                                 "user": os.getenv("USER", "unknown")}))

        log_kubectl_command(logger, cmd,
                           function_name="execute_kubectl_command")
        result = subprocess.run(cmd, capture_output=True, text=True,
                                check=True)
        return f"kubectl output:\nCommand: {cmd_str}\n\n{result.stdout}"
    except subprocess.CalledProcessError as e:
        log_kubectl_command(logger, cmd,
                           function_name="execute_kubectl_command",
                           success=False, error_msg=str(e.stderr))
        return f"Error running kubectl command: {e.stderr}"
    except Exception as e:
        log_kubectl_command(logger, cmd,
                           function_name="execute_kubectl_command",
                           success=False, error_msg=str(e))
        return f"Error: {e}"


# ---- Main loop -----------------------------------------------------------

def interactive_kubernetes_assistant():
    """Interactive Kubernetes assistant that runs real kubectl commands."""
    logger = setup_logging()

    if not os.getenv("OPENAI_API_KEY"):
        print("ERROR: OPENAI_API_KEY environment variable is not set.")
        print("Run: export OPENAI_API_KEY='your-key-here'")
        logger.error("OPENAI_API_KEY not set")
        return

    kubectl_available, kubectl_msg = check_kubectl()
    if not kubectl_available:
        print(f"ERROR: {kubectl_msg}")
        print("Install kubectl and configure it for your cluster.")
        logger.error("kubectl not available: %s", kubectl_msg)
        return

    print("Interactive Kubernetes Assistant")
    print("=" * 50)
    print(f"  {kubectl_msg}")
    print("Ask about pods, logs, or any Kubernetes operations.")
    print("Type 'quit' to exit.\n")
    logger.info("Interactive Kubernetes Assistant started")

    client = OpenAI()  # reads OPENAI_API_KEY and OPENAI_BASE_URL from env

    function_map = {
        "get_kubernetes_pods": lambda **kw: get_kubernetes_pods(logger, **kw),
        "get_pod_logs": lambda **kw: get_pod_logs(logger, **kw),
        "describe_pod": lambda **kw: describe_pod(logger, **kw),
        "execute_kubectl_command": lambda **kw: execute_kubectl_command(logger, **kw),
    }

    conversation_history = [
        {
            "role": "system",
            "content": (
                "You are a helpful DevOps assistant that interacts with "
                "Kubernetes clusters using kubectl commands. You can get "
                "pod information, logs, and descriptions. Always provide "
                "clear explanations. Remember previous interactions in "
                "this conversation."
            ),
        },
    ]

    while True:
        try:
            user_input = input(
                "\nWhat would you like to know about your cluster? "
            )

            if user_input.lower() in ("quit", "exit", "q"):
                print("Goodbye.")
                logger.info("=== Session Ended ===")
                break

            if not user_input.strip():
                continue

            logger.info("USER_INPUT: %s", user_input)
            conversation_history.append(
                {"role": "user", "content": user_input}
            )

            # Step 1: model decides which tool(s) to call
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=conversation_history,
                tools=TOOLS,
                tool_choice="auto",
            )

            message = response.choices[0].message

            if message.tool_calls:
                n = len(message.tool_calls)
                print(f"\n[tool] Running {n} kubectl "
                      f"command{'s' if n > 1 else ''}...")

                conversation_history.append({
                    "role": "assistant",
                    "content": message.content,
                    "tool_calls": message.tool_calls,
                })

                # Step 2: execute every tool call
                for i, tool_call in enumerate(message.tool_calls):
                    fn_name = tool_call.function.name
                    args = json.loads(tool_call.function.arguments)

                    if n > 1:
                        print(f"  [{i + 1}/{n}] {fn_name}")

                    if fn_name in function_map:
                        output = function_map[fn_name](**args)
                    else:
                        output = f"Unknown function: {fn_name}"
                        logger.error("UNKNOWN_FUNCTION: %s", fn_name)

                    conversation_history.append({
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "content": output,
                    })

                # Step 3: model summarises the results
                follow_up = client.chat.completions.create(
                    model="gpt-4o",
                    messages=conversation_history,
                )

                final = follow_up.choices[0].message.content
                print(f"\n{final}")
                conversation_history.append(
                    {"role": "assistant", "content": final}
                )

            else:
                text = message.content
                print(f"\n{text}")
                conversation_history.append(
                    {"role": "assistant", "content": text}
                )

        except KeyboardInterrupt:
            print("\nGoodbye.")
            logger.info("=== Session interrupted (Ctrl+C) ===")
            break
        except Exception as e:
            print(f"\nError: {e}")
            logger.error("GENERAL_ERROR: %s", e)


if __name__ == "__main__":
    interactive_kubernetes_assistant()
